http:
  enabled: true
  address: 0.0.0.0:4195
  root_path: /benthos
  debug_endpoints: false
  cert_file: ""
  key_file: ""
  cors:
    enabled: false
    allowed_origins: []
  basic_auth:
    enabled: false
    realm: restricted
    username: ""
    password_hash: ""
    algorithm: sha256
    salt: ""
input:
  broker:
    inputs:
      - batched:
          child:
            broker:
              inputs:
                - stdin: {}
                - http_server: {}
          policy:
            check: this.contains("END BATCH")
buffer:
  none: {}
pipeline:
  threads: -1
  processors: []
output:
  fallback:
    - reject_errored:
        questdb:
          address: localhost:9000
          table: hello3
          max_in_flight: 256
          timestampFields:
            - t
          designatedTimestampField: "d"

    - stdout: {}


input_resources: []
processor_resources: []
output_resources: []
cache_resources: []
rate_limit_resources: []
logger:
  level: DEBUG
  format: logfmt
  add_timestamp: false
  level_name: level
  timestamp_name: time
  message_name: msg
  static_fields:
    '@service': benthos
  file:
    path: ""
    rotate: false
    rotate_max_age_days: 0
metrics:
  prometheus: {}
  mapping: ""
tracer:
  none: {}
shutdown_delay: 0s
shutdown_timeout: 20s
tests: []
